pustaklaya_django/pustak/urls.py
from django.urls import path
from .views import user_signup, user_login, index, upload_book, user_logout, book_view, RegisterView, LoginView, UserDetailsView, BookListView, BookUploadAPIView, BookDetailView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("signup/", user_signup, name="signup"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("book/<str:book_title>/", book_view, name="book_view"),
    path("", index, name="index"),
    path('upload/', upload_book, name='upload_book'),
    path('api/register/', RegisterView.as_view(), name='register'),
    path('api/login/', LoginView.as_view(), name='login'),
    path('api/userdetail/', UserDetailsView.as_view(), name='user-details'),
    path('api/books/', BookListView.as_view(), name='book-list'),
    path('api/upload/', BookUploadAPIView.as_view(), name='book-upload'),
     path('api/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pustaklaya_django/pustaklaya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pustak.urls')),
]

pustaklaya_django/pustak/models.py
from django.db import models

class Pustak(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    info = models.TextField(max_length=500, null=True)
    genre = models.CharField(max_length=255)
    book_cover = models.ImageField(upload_to='book_covers/', null=True)  # Specify the directory for storing book cover images
    pdf_file = models.FileField(upload_to='books/', null=True, blank=True)

    def __str__(self):
        return self.title

pustaklaya_django/pustak/forms.py
from django import forms
from .models import Pustak

class PustakForm(forms.ModelForm):
    class Meta:
        model = Pustak
        fields = ['title', 'author', 'info', 'genre', 'book_cover', 'pdf_file']

pustaklaya_django/pustak/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from .forms import PustakForm
from .models import Pustak
from django.utils.text import slugify
from django.contrib.auth.models import User
from .serializers import UserSerializer, UserDetailsSerializer, UserWithPasswordSerializer, BookViewSerializer, BookUploadSerializer
from rest_framework import generics, permissions, exceptions, serializers, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.tokens import RefreshToken
class BookUploadAPIView(APIView):
    queryset = Pustak.objects.all()
    serializer_class = BookUploadSerializer
    def post(self, request, *args, **kwargs):
        
        serializer = BookUploadSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserWithPasswordSerializer
    permission_classes = (permissions.AllowAny,)

    def perform_create(self, serializer):
        user = serializer.save()
        user.set_password(serializer.validated_data['password'])
        user.save()
class LoginView(APIView):
    serializer_class = UserSerializer
    permission_classes = (permissions.AllowAny,)

    def post(self, request, *args, **kwargs):
        username = request.data.get('username', '')
        password = request.data.get('password', '')
        user = User.objects.filter(username=username).first()

        if user is None or not user.check_password(password):
            raise serializers.ValidationError({'detail': 'Invalid credentials'}, code='authentication_failed')

        refresh = RefreshToken.for_user(user)
        
        return Response({
            'refresh': str(refresh),
            'access': str(refresh.access_token),
        })

class UserDetailsView(generics.RetrieveAPIView):
    serializer_class = UserDetailsSerializer
    permission_classes = [IsAuthenticated]

    def get_object(self):
        # The user is available through the request due to IsAuthenticated permission
        user = self.request.user

        if not user.is_authenticated:
            raise exceptions.NotAuthenticated(detail="User not authenticated", code="user_not_authenticated")

        return user

class BookListView(generics.ListAPIView):
    queryset = Pustak.objects.all()
    serializer_class = BookViewSerializer
class BookDetailView(generics.RetrieveAPIView):
    queryset = Pustak.objects.all()
    serializer_class = BookViewSerializer

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data, status=status.HTTP_200_OK)

def index(request):
    books = Pustak.objects.all()
    return render(request, 'index.html', {'pustaks':books})

def upload_book(request):
    if request.method == 'POST':
        form = PustakForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')  # Redirect to a view displaying a list of books
    else:
        form = PustakForm()
    return render(request, 'upload_book.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect('index')
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Signup successful. You are now logged in.')
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})
def user_logout(request):
    logout(request)
    messages.success(request, 'Logout successful.')
    return redirect('index')
def book_view(request, book_title):
    # URL parameters might have special characters, so slugify them
    slugified_title = slugify(book_title)
    
    # Query the database using the slugified title
    pustak = get_object_or_404(Pustak, title__iexact=slugified_title)

    return render(request, 'book_view.html', {'pustak': pustak})

pustaklaya_django/pustak/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Pustaklaya{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <!-- Add this in the head section of your base.html or book_view.html -->
<!-- Add this in the head section of your base.html or book_view.html -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
<style>
    #flipbook:hover {
        transform: perspective(1000px) rotateY(180deg);
    }
</style>



</head>

<body class="bg-gray-800 text-white font-sans">

    <header class="bg-gray-700 p-4 text-center">
        <h1 class="text-2xl">{% block header %}Pustaklaya{% endblock %}</h1>
    </header>

    <nav class="bg-gray-600 p-4 text-center">
        <a href="{% url 'index' %}" class="text-white hover:text-gray-300">Home</a>
        {% if user.is_authenticated %}
        <a href="{% url 'upload_book' %}" class="text-white hover:text-gray-300">Upload</a>
        <a href="{% url 'logout' %}" class="text-white hover:text-gray-300">Logout</a>
        {% else %}
        <a href="{% url 'signup' %}" class="text-white hover:text-gray-300">Sign Up</a>
        <a href="{% url 'login' %}" class="text-white hover:text-gray-300">Login</a>
        {% endif %}
    </nav>

    <main class="p-4">
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-gray-700 p-4 text-center  bottom-0 w-full">
        &copy; 2024 Pustaklaya
    </footer>

</body>

</html>

pustaklaya_django/pustak/templates/book_view.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-3xl font-bold mb-4">{{ pustak.title }}</h1>

    <div id="pdf-gallery" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div class="bg-white p-4 rounded-lg shadow-md">
            <object data="../..{{ pustak.pdf_file.url }}" type="application/pdf" class="w-full h-64 md:h-72 lg:h-80" aria-label="{{ pustak.title }}"></object>
        </div>
    </div>
{% endblock %}

pustaklaya_django/pustak/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-3xl font-bold mb-4">Our Books</h1>

    <div class="flex flex-wrap -mx-4">
        {% for book in pustaks %}
            <a href="{% url 'book_view' book_title=book.title|slugify %}" class="w-full md:w-1/2 lg:w-1/3 xl:w-1/4 p-4">
                <div class="bg-gray-800 rounded-lg overflow-hidden">
                    <img src="{{ book.book_cover.url }}" class="w-full h-40 object-cover object-center" alt="{{ book.title }}">
                    <div class="p-4">
                        <h2 class="text-lg font-semibold mb-2">{{ book.title }}</h2>
                        <p class="text-gray-400">{{ book.info }}</p>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

pustaklaya_django/pustak/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 id="log" class="text-center mb-4">Login</h2>
        <form method="post" action="{% url 'login' %}" class="max-w-md mx-auto">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="mb-3">
                {{ form.password.label_tag }}
                {{ form.password }}
            </div>
            <button type="submit"
                class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline-blue active:bg-blue-800">
                Login
            </button>
        </form>
    </div>
{% endblock %}

pustaklaya_django/pustak/templates/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 id="log" class="text-center mb-4">Signup</h2>
        <form method="post" action="{% url 'signup' %}" class="max-w-md mx-auto">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="mb-3">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
            </div>
            <button type="submit"
                class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline-green active:bg-green-800">
                Signup
            </button>
        </form>
    </div>
{% endblock %}

pustaklaya_django/pustak/templates/upload_book.html
{% extends 'base.html' %}

{% block title %}Upload Book{% endblock %}

{% block content %}
    <h2 class="text-3xl font-bold mb-4">Upload Book</h2>

    <form method="post" enctype="multipart/form-data" class="max-w-md mx-auto">
        {% csrf_token %}

        <!-- Customize styles for form elements -->
        <div class="text-gray-600 mb-4">
            <label for="id_title" class="block text-gray-600 font-bold mb-2">Title</label>
            {{ form.title }}
        </div>

        <div class="text-gray-600 mb-4">
            <label for="id_author" class="block text-gray-600 font-bold mb-2">Author</label>
            {{ form.author }}
        </div>

        <div class="text-gray-600 mb-4">
            <label for="id_book_cover" class="block text-gray-600 font-bold mb-2">Book Cover</label>
            {{ form.book_cover }}
        </div>
        <div class="text-gray-600 mb-4">
          <label for="id_info" class="block text-gray-600 font-bold mb-2">Genre</label>
          {{ form.genre }}
        </div>
        <div class="text-gray-600 mb-4">
            <label for="id_info" class="block text-gray-600 font-bold mb-2">Info</label>
            {{ form.info }}
        </div>
        <div class="text-gray-600 mb-4">
          <label for="id_info" class="block text-gray-600 font-bold mb-2">Pdf File</label>
          {{ form.pdf_file }}
        </div>

        <button type="submit"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:shadow-outline-blue active:bg-blue-800">
            Upload
        </button>

        {% if form.errors %}
            <p class="text-red-500">{{ form.errors }}</p>
        {% endif %}
    </form>
{% endblock %}